<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Personas</title>
        <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" >
        <link rel="stylesheet" type="text/css" href="css/mystyle.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    </head>
    <body>
        <?php require_once("menu_view.phtml"); ?>

        <div class="container">            
            <div class="row">
                <div class="col-sm-12 mb-3">
                    <div class="card">
                      <div class="card-header">
                        Buscador
                      </div>
                      <div class="card-body">
                        <div class="row">
                            <div class="col-sm-4"></div>
                            <div class="col-sm-3">
                                  <label for="Buscador_fechaDesde" class="form-label">Fecha Desde</label>
                                  <input class="form-control datepicker" id="Buscador_fechaDesde" placeholder="Fecha Desde">
                            </div>
                            <div class="col-sm-3">
                                  <label for="Buscador_fechaHasta" class="form-label">Fecha Hasta</label>
                                  <input class="form-control datepicker" id="Buscador_fechaHasta" placeholder="Fecha Hasta">
                            </div>
                            <div class="col-sm-2">
                                <br/>
                                <button class="btn btn-info" id='Buscador_btnbuscar'>Buscar</button>
                                <button class="btn btn-warning" id='Buscador_btnlimpiar'>Limpiar</button>
                            </div>
                        </div> 
                      </div>
                    </div>
                </div>

                <div class="row" id='loadblogs'>
                <?php
                    foreach ($datos as $dato) {
                        $idblog = $dato["idblog"];
                        echo '<div class="col-sm-4 mb-3">
                                <div class="card">
                                    <img src="https://picsum.photos/200/200?random='.$idblog.'" width="100%" height="250px">
                                    <div class="card-body">
                                        <h5 class="card-title">'.$dato["titulo"].'</h5>
                                        <p class="card-text fw-light fs-6 " style="text-align: justify;">'.$dato["descripcion"].'</p>
                                        <p class="card-text text-end"><small class="text-muted">'.date("d/m/Y", strtotime($dato["createdate"])).'</small></p>
                                    </div>
                                </div>
                            </div>';
                    }
                ?>  
                </div>             
            </div>
        </div>

        
        <?php require_once("modals_view.phtml"); ?>
        <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
        <script src="vendor/jquery/jquery-3.6.1.min.js"></script>
        <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
        <script src="jquery/functions.js?v=<?php echo time(); ?>"></script>
    </body>
</html>
