<header class="p-3 mb-3 border-bottom">
            <div class="container">
              <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                  <img src="img/logoipsum-259.svg" width="80%">
                </a>

                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                </ul>

                <div class="dropdown text-end">
                  <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="img/avatar.png" alt="mdo" width="32" height="32" class="rounded-circle">
                  </a>
                  <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">

                    <?php
                      if($session_idusario != ''){
                        echo '<li><p>'.$session_nombre.' '.$session_apellido.'</p></li>
                          <li><hr class="dropdown-divider"></li>
                          <li><a class="dropdown-item" href="#">Sign out</a></li>';
                      }else{
                        echo '<li><a class="dropdown-item" data-bs-toggle="modal" data-bs-target="#ModalLogin">Login</a></li>';
                      }
                    ?>
 
                    
                  </ul>
                </div>
              </div>
            </div>
        </header>