<!-- Modal -->
<div class="modal fade" id="ModalLogin" tabindex="-1" aria-labelledby="ModalLoginLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLoginLabel">Iniciar Sesion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <div class="mb-3">
          <label for="ModalLogin_Correo" class="form-label">Correo</label>
          <input type="email" class="form-control" id="ModalLogin_Correo" placeholder="Correo">
        </div>

        <div class="mb-3">
          <label for="ModalLogin_contrasena" class="form-label">Contraseña</label>
          <input type="password" class="form-control" id="ModalLogin_contrasena" placeholder="Contraseña">
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary">Iniciar Sesion</button>
      </div>
    </div>
  </div>
</div>