<!-- Modal -->
<div class="modal fade" id="ModalLogin" tabindex="-1" aria-labelledby="ModalLoginLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalLoginLabel">Iniciar Sesion</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <div class="mb-3">
          <label for="ModalLogin_Correo" class="form-label">Correo</label>
          <input type="email" class="form-control" id="ModalLogin_Correo" placeholder="Correo">
        </div>

        <div class="mb-3">
          <label for="ModalLogin_contrasena" class="form-label">Contraseña</label>
          <input type="password" class="form-control" id="ModalLogin_contrasena" placeholder="Contraseña">
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id='ModalLogin_btniniciarsesion'>Iniciar Sesion</button>
      </div>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="ModalRegistro" tabindex="-1" aria-labelledby="ModalRegistroLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalRegistroLabel">Registro</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        
        <div class="mb-3">
          <label for="ModalRegistro_Nombre" class="form-label">Nombre</label>
          <input type="text" class="form-control" id="ModalRegistro_Nombre" placeholder="Nombre">
        </div>

        <div class="mb-3">
          <label for="ModalRegistro_Apellido" class="form-label">Apellido</label>
          <input type="text" class="form-control" id="ModalRegistro_Apellido" placeholder="Apellido">
        </div>

        <div class="mb-3">
          <label for="ModalRegistro_FechaNacimiento" class="form-label">Fecha de Nacimiento</label>
          <input data-date-format="mm/dd/yyyy" class="form-control datepicker" id="ModalRegistro_FechaNacimiento" placeholder="Fecha de Nacimiento">
        </div>

        <div class="mb-3">
          <label for="ModalRegistro_Correo" class="form-label">Correo</label>
          <input type="email" class="form-control" id="ModalRegistro_Correo" placeholder="Correo">
        </div>

        <div class="mb-3">
          <label for="ModalRegistro_contrasena" class="form-label">Contraseña</label>
          <input type="password" class="form-control" id="ModalRegistro_contrasena" placeholder="Contraseña">
        </div>

        <div class="mb-3">
          <label for="ModalRegistro_repetircontrasena" class="form-label">Repetir Contraseña</label>
          <input type="password" class="form-control" id="ModalRegistro_repetircontrasena" placeholder="Contraseña">
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="ModalRegistro_btnregistrar">Registrar</button>
      </div>
    </div>
  </div>
</div>